console.log('++++ Show arrays ++++')
// console.log(pointsperdetarr)
console.log(detrosterarr)
console.log(rosterarr)
console.log(selectarr)
// console.log(unitarr)
console.log(detachmentsarr)
// console.log(specialrulesarr)
// console.log(adaptationarr)
// console.log(traitsarr)
// console.log(relicsarr)
// console.log(magicarr)
console.log('++++ Stop ++++')