var ability = {
	//	Basic command ability
		'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero pse.',
	//	Legion abilities
		'Endless Legions' : 'Choose a gravesite within 9\". You may pick a friendly <b>SUMMONABLE</b> unit that has been destroyed and set it up again wholly within 9\" of that gravesite and more than 9\" from any enemy models.',
		'The Unquiet Dead' : 'After territories have been determined, but before any units have been set up, you may pick up to 2 points in your territory and up to 2 points anywhere on the battlefield to be gravesites. You may wish to place suitable markers on these points. Instead of setting up a <b>SUMMONABLE</b> unit on the battlefield, you can place it to one side and say that it is set up in the grave. You can do this with as many units as you wish.<p>At the end of your movement phase, for each <b>DEATH HERO</b> within 9\" of a gravesite, you may pick a single unit in the grave and set it up wholly within 9" of that gravesite and more than 9\" from any enemy models. Any model that is unable to be set up in this way is slain. If a unit is still in the grave at the end of the battle, it is considered to be slain.</p><i>Gravesites have the following ability:</i><br><b>Invigorating Aura</b>: At the start of your hero phase, pick a friendly <b>SUMMONABLE</b> unit within 9\" of this gravesite. You can either heal D3 wounds that have been allocated to it or, if no wounds are currently allocated to the unit, you may return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
		'Deathless Minions' : 'Roll a dice each time you allocate a wound or mortal wound to a friendly <b>DEATH</b> unit within 6\" of your general or another friendly <b>DEATH HERO</b>. On a 6+ the wound is negated.',
	//	Unit abilities
		'Ethereal' : 'Ignore modifiers (positive or negative) when making save rolls for this model.',
		'FLY' : 'This unit can fly.',
		'The Hunger' : 'At the end of any combat phase in which this model slew any enemy models, you can heal 1 wound that has been allocated to it.',
		'Standard Bearer' : 'Models in this unit may be Standard Bearers. Substract 1 from the Bravery characteristic of enemy units whilst they are within 6\" of any <b>DEATH</b> Standard Bearers.',
		'Hornblower' : 'Models in this unit may be Hornblowers. A unit that includes any Hornblowers can always move up to 6\" when it charges, unless its charge roll is higher.',
		'Crypt Shields' : 'Add 1 to the save rolls for a unit carrying Crypt Shields against attacks that have a Rend characteristic of "-".',
		'Serve in Death' : 'You can add 1 to hit rolls for this unit if it is wholly within 18" of any friendly <b>Death Heroes</b>.',
}

var legions = {
	grandhostofnagash : {
		armyname : 'Grand Host of Nagash',
		commandability : {
			'Endless Legions' : '#',
		},
		battletraits : {
			'The Unquiet Dead' : '#',
			'Deathless Minions' : '#',
			'Chosen Guardians' : 'Add 1 to the Attacks characteristic of all melee weapons used by <b>GRAND HOST OF NAGASH MORGHAST</b> units.',
			'Legions Innumerable' : 'In your hero phase, you may roll a dice for each friendly <b>GRAND HOST OF NAGASH SUMMONABLE</b> unit on the battlefield. On a 5+ you can heal up to D3 wounds that have been allocated to it. For units with a Wounds characteristic of 1, return 1 slain model to the unit for each wound that would have been healed.',
		},
		commandtraits : {
			'Master of Death' : 'Re-roll results of 1 (i.e. rolls of 1-2 on a D3) for friendly units affected by a Deathly Invocation ability that are within 12\" of this general.',
			'Chosen Champion' : 'Add 1 to the Damage characteristic of melee weapons used by this general for attacks made against enemy <b>HEROES</b>.',
			'Bane of the Living' : 'Re-roll wound rolls of 1 for this general for attacks made against enemy units that do not have the <b>DEATH</b> keyword.',
			'Aura of Ages' : 'At the start of the combat phase, roll a dice for each enemy unit within 3\" of this general. On a 4+ subtract 1 from hit rolls made for that unit until the end of the combat phase.',
			'Ancient Strategist' : 'Re-roll failed charge rolls for friendly <b>DEATHRATTLE</b> and <b>MORGHAST</b> units that are within 9\" of this general.',
			'Lord of Nagashizzar' : 'Add 1 to the Attacks characteristic of melee weapons used by friendly <b>DEATHRATTLE</b> units that are within 6\" of this general.',
		},
		artefacts : {
			'Deathforged Chain' : 'At the start of your hero phase, the bearer heals 1 wound that has been allocated to it.',
			'Balefire Lantern' : 'Subtract 1 from wound rolls for enemy units within 6\" of the bearer. In addition, re-roll successful casting rolls for enemy <b>WIZARDS </b> within 6\" of the bearer.',
			'Grave-sand Timeglass' : 'Whilst the bearer is on the battlefield, once per battle, in your hero phase, you can pick an enemy <b>HERO</b> on the battlefield. The enemy hero suffers D3 mortal wounds. At the start of each of your subsequent hero phases, roll a dice. On a 4+ the enemy hero suffers 1 mortal wound.',
			'Ossific Diadem' : 'Roll a dice each time you allocate a wound or mortal wound to a friendly <b>DEATHRATTLE</b> model within 12\" of the bearer. On a 6+ the wound is negated.',
			'Amethyst Shard' : 'Once per battle, in your hero phase, you can declare that the bearer will merge the shard with one of their melee weapons. Pick one of the bearer’s melee weapons. Until your next hero phase, add 1 to hit and wound rolls made for that weapon.',
			'Terrorgheist Mantle' : 'In your shooting phase, you can declare that the bearer will unleash a death shriek. Pick an enemy unit within 10\" of the bearer and roll 2 dice. If the total is higher than the enemy unit’s Bravery characteristic, it suffers a number of mortal wounds equal to the difference.',
		},
	},
	legionofsacrament : {
		armyname : 'Legion of Sacrament',
		commandability : {
			'Endless Legions' : '#',
		},
		battletraits : {
			'The Unquiet Dead' : '#',
			'Deathless Minions' : '#',
			'The Master\'s Teachings' : 'Whenever an enemy unit is destroyed, before removing the last model, you may pick one of your gravesites within 6\" of that model.<br>Roll a dice, then remove the model.<br>On a 4+, you may pick a friendly <b>SUMMONABLE</b> unit that has been destroyed and set it up again wholly within 9\" of that gravesite and more than 9\" from any enemy models.',
			'The Black Disciples' : 'Friendly <b>LEGION OF SACRAMENT WIZARDS</b> may add 1 to casting rolls.',
		},
		commandtraits : {
			'Emissary of the Master' : 'You can re-roll failed charge rolls for friendly <b>DEATH</b> units that are within 6\" of this general at the start of the charge phase.',
			'Mark of the Favoured' : 'Each time this general is selected as the target of an attack in the combat phase, roll a dice. On a 6+ the attacking unit suffers a mortal wound.',
			'Dark Acolyte' : 'This general is a <b>WIZARD</b> that knows the Arcane Bolt and Mystic Shield spells, as well as a single spell from one of the Lores of the Dead.<br>If this general is already a <b>WIZARD</b>, they may generate an additional spell from one of the Lores of the Dead.',
			'Mastery of Death' : 'At the start of your hero phase, all friendly <b>DEATH</b> units within 6\" of this general may immediately make a move of up to 3\" as if it were your movement phase. They may not run as part of this move.',
			'Peerless Commander' : 'This general may summon a unit from a gravesite (see below) whilst they are within 12\" rather than 9\".',
			'Bound to the Master' : 'This general may use Arkhan the Black\'s First of the Mortarchs command ability (pg 97)',
			'* First of the Mortarchs' : 'Until the end of the hero phase all friendly <b>DEATH WIZARDS</b> within 18" of him can increase the range of their spells by 6\".',
		},
		artefacts : {
			'Spiritcage' : 'Whenever an enemy <b>HERO</b> is slain within 6\" of the bearer, add 1 to wound rolls for friendly <b>DEATH</b> units within 12\" of the bearer until the end of the turn.',
			'Shroud of Darkness' : 'Substract 1 from the hit rolls of attacks that target the bearer in the shooting phase if the attacking unit is within 8\" of the bearer.<br>Substract 2 from the hit rolls of attacks that target the bearer in the shooting phase if the attacking unit more than 8\" away from the bearer.',
			'Asylumaticae' : 'Once per battle, in your hero phase, you can declare that the bearer will open the Asylumaticae.<br>If you do so, roll a dice. On a 1 the bearer suffers a mortal wound. On a 2+ each enemy unit within 12\" of the bearer suffers 1 mortal wound.',
			'Wristbands of Black Gold' : 'Roll a dice each time you allocate a wound or mortal wound to the bearer in the shooting phase. On a 4+ the wound is negated.',
			'Azyrbane Standard' : 'Substract 1 from wound rolls for enemy units within 6\" of the bearer.<br>In addition, re-roll successful casting rolls for <b>ORDER WIZARDS</b> within 6\" of the bearer.',
			'Black Gem' : 'Once per battle, in your hero phase, you can declare that the bearer will shatter the Black Gem. Pick a point on the battlefield within 8\" of the bearer.<br>Roll a dice for each unit within 3\" of this point. On a 6+, one model from that unit is slain.<br>If the unit has any models with wounds allocated to it, then that model must be the model that is slain.',
		},
	},
	legionofblood : {
		armyname : 'Legion of Blood',
		commandability : {
			'Endless Legions' : '#',
		},
		battletraits : {
			'The Unquiet Dead' : '#',
			'Deathless Minions' : '#',
			'Immortal Majesty' : 'Subtract 1 from the Bravery characteristic of enemy units within 6\" of any friendly <b>LEGION OF BLOOD</b> units.',
			'Favoured Retainers' : 'Add 1 to the Attacks characteristic of all melee weapons used by friendly <b>LEGION OF BLOOD VAMPIRE LORDS</b> and <b>LEGION OF BLOOD</b> Blood Knights.',
		},
		commandtraits : {
			'Swift Strikes' : 'Each time you make a hit roll of 6+ in the combat phase for this general, you can make one additional hit roll for the same weapon against the same target.',
			'Soul-crushing Contempt' : 'If this general slays any models in the combat phase, subtract 1 from the Bravery characteristic of the slain model’s unit until the end of the turn.',
			'Aristocracy of Blood' : 'You can re-roll failed charge rolls for friendly <b>SOULBLIGHT</b> units that are within 9\" of this general at the start of the charge phase.',
			'Aura of Dark Majesty' : 'Subtract 1 from the hit rolls of attacks that target this general in the combat phase.',
			'Walking Death' : 'If the hit roll for an attack made with one of this general’s melee weapons is 6+, do not roll to wound. Instead, the target suffers a number of mortal wounds equal to the Damage characteristic of that weapon.',
			'Sanguine Blur' : 'Add 2\" to this general’s Move characteristic. In addition, you can re-roll failed charge rolls for this general.',
		},
		artefacts : {
			'Ring of Dominion' : 'When the bearer is selected to fight in the combat phase, you can pick an enemy model within 3\" of them and roll a dice. On a 5+ you can pick a melee weapon that the enemy model is armed with (though not one that has a value for one or more characteristics that is given as ‘*’ or ‘See below’). For this combat phase, the bearer of this ring may attack with that weapon in addition to their own.',
			'Shadeglass Decanter' : 'After armies have been set up but before the first battle round, select an enemy <b>HERO</b>. In your hero phase, as long as that hero is on the battlefield, you can roll a dice. If the result is higher than the number of the current battle round, that hero suffers 1 mortal wound.',
			'Orb of Enchantment' : 'Once per battle, at the start of the combat phase, you can pick an enemy <b>HERO</b> within 3\" of the bearer. In that combat phase, that enemy hero may not pile in, attack or use abilities. ',
			'Soulbound Garments' : 'Re-roll save rolls of 1 for the bearer.',
			'Oubliette Arcana' : 'When an enemy <b>WIZARD</b> successfully casts a spell within 30\" of the bearer, instead of attempting to unbind it you can declare that the Oubliette Arcana will attempt to capture the magical energies. Roll a dice. On a 6+ the spell is negated and has no effect. In addition, that spell may not be cast again by that <b>WIZARD</b> for the rest of the battle.',
			'Amulet of Screams' : 'Once per battle, when an enemy <b>WIZARD</b> successfully casts a spell, instead of attempting to unbind it you can declare that the bearer will use the Amulet of Screams. If you do so, roll a dice. On a 2+ the spell is negated and has no effect.',
		},
	},
	legionofnight : {
		armyname : 'Legion of Night',
		commandability : {
			'Endless Legions' : '#',
		},
		battletraits : {
			'The Unquiet Dead' : '#',
			'Deathless Minions' : '#',
			'The Bait' : 'Add 1 to save rolls for friendly <b>LEGION OF NIGHT DEATHRATTLE</b> units that are wholly within your territory.',
			'Ageless Cunning' : 'Instead of setting up a <b>LEGION OF NIGHT</b> unit on the battlefield, you can place it to one side and say that it is set up in ambush. You can do this with up to 3 units. At the end of any of your movement phases, you can set up any of the units in ambush wholly within 6\" of any battlefield edge and more than 9\" away from any enemy models.',
		},
		commandtraits : {
			'Above Suspicion' : 'This general may be set up in ambush in addition to the 3 units normally allowed by the Ageless Cunning battle trait (see below).',
			'Swift Form' : 'Add 2\" to this general’s Move characteristic. In addition, add 2\" to the distance they can move when they run.',
			'Unbending Will' : 'Friendly <b>LEGION OF NIGHT</b> units within 12\" of this general may re-roll failed battleshock tests.',
			'Merciless Hunter' : 'Re-roll wound rolls of 1 for this general.',
			'Unholy Impetus' : 'If this general slays any models in the combat phase, pick a friendly <b>LEGION OF NIGHT</b> unit within 3\" of the general. Add 1 to the Attacks characteristic of that unit’s melee weapons until the end of the phase.',
			'Terrifying Visage' : 'Subtract 1 from the Bravery characteristic of enemy units within 6\" of this general.',
		},
		artefacts : {
			'Vial of the Pure Blood' : 'Once per battle, in your hero phase, you can declare that the bearer will drink from the Vial of Pure Blood. If you do so, you can add 1 to hit and wound rolls for the bearer until your next hero phase.',
			'Shard of Night' : 'Subtract 1 from the hit rolls of attacks that target the bearer in the shooting phase.',
			'Gem of Exsanguination' : 'Once per battle, at the start of the combat phase, you can pick an enemy unit within 6\" of the bearer and roll a dice. On a 1 nothing happens. On a 2-5 the unit suffers D3 mortal wounds. On a 6+ the unit suffers D6 mortal wounds.',
			'Chiropteric Cloak' : 'At the start of the combat phase, you can declare that the bearer will feed the Chiropteric Cloak. If you do so, the bearer suffers 1 mortal wound. During that combat phase, each time the hit roll of an attack that targets the bearer is 1 or less, the attacking unit suffers 1 mortal wound after all its attacks have been resolved.',
			'Morbheg\'s Claw' : 'In your hero phase, you can declare that the bearer will carve sigils in the ground with this claw. If you do so, they may not move, charge or attack this turn, but you can add 2 to casting rolls made for friendly <b>LEGION OF NIGHT WIZARDS</b> within 12" of the bearer.',
			'Curseblade' : 'After armies have been set up but before the first battle round begins, you can pick an enemy <b>HERO</b>. In your hero phase, as long as the enemy hero is on the battlefield, you can roll a dice. On a 4+ that enemy hero suffers 1 mortal wound and you may heal a wound that has been allocated to the bearer.',
		},
	},
	soulblight : {
		armyname : 'Allegiance: SOULBLIGHT',
		commandability : {
			'Inspiring Presence' : '#',
		},
		battletraits : {
			'Deathless Thralls' : 'Roll a dice each time you allocate a wound or mortal wound to a friendly <b>SOULBLIGHT</b> unit within 6\" of your general or another <b>SOULBLIGHT HERO</b> from your army. On a 6+ the wound is negated.',
			'The Bloodlines' : 'Before you select your general’s command trait, pick one of the following bloodlines for the army to have. The associated traits apply to all <b>SOULBLIGHT</b> units from your army for the duration of the battle, even if the general is slain (if you must select a new general during the battle, do not generate a new bloodline for the army).',
			'* Dragon Warriors' : 'You can re-roll hit rolls of 1 for models that have the Dragon Warriors bloodline if they charged in the same turn.',
			'* Lords of Night' : 'Models with the Lords of Night bloodline receive the benefits of the Deathless Thralls battle trait even if they are not within 6\" of the general or another friendly <b>SOULBLIGHT HERO</b>.',
			'* Necromantic' : 'Add 1 to casting and unbinding rolls for <b>WIZARDS </b> with the Necromantic bloodline. In addition, subtract 1 from the Bravery characteristic of enemy units that are within 6\" of one or more models with the Necromantic bloodline.',
			'* Swift Death' : 'Add 2\" to the Move characteristic of all models that have the Swift Death bloodline. In addition, Swift Death models can always move as if they can fly.',
		},
		commandtraits : {
			'Curse of the Revenant' : 'Add 1 to this general’s Wounds characteristic.',
			'Deathless Duelist' : 'Re-roll hits rolls of 1 for this general when they attack an enemy <b>HERO</b> in the combat phase.',
			'Transfix' : 'At the start of the combat phase, pick one enemy <b>HERO</b> within 3" of this general. Until the end of the phase, subtract 1 from hit rolls for the model you picked when it targets the general.',
			'Mist Form' : 'If this general retreats, they can move as if they can fly and they can still charge in the same turn.',
			'Killing Blow' : 'Wound rolls of 6+ for attacks made by this general in the combat phase inflict a mortal wound in addition to any other damage they inflict.',
			'Blood Fury' : 'Add 1 to the Attacks characteristic of melee weapons used by this general.',
		},
		artefacts : {
			'The Slaking Blade' : 'Pick one of the bearer’s melee weapons. Keep a tally of the number of wounds allocated as a result of attacks made with that weapon. As soon as the total reaches 6 or more, the bearer heals D3 wounds that have been allocated to them, and you can add 1 to the Damage characteristic of that weapon for the rest of the battle.',
			'The Scabbing Plate' : 'At the end of any combat phase in which the bearer caused any wounds to be allocated to any enemy models, you can heal 1 wound that has been allocated to the bearer.',
			'Crimson Wing' : 'In your shooting phase, you can pick an enemy unit within 30" of the bearer and roll a dice. On a roll of 3+ that unit suffers 1 mortal wound.',
			'Sigil of the Sanguine Throne' : 'Once per charge phase, you can re-roll a failed charge roll made for a friendly <b>VAMPIRE</b> unit within 12\" of the bearer.',
			'The Saccharine Goblet' : 'At start of the combat phase, you can declare that the bearer will drink from the Saccharine Goblet. If you do so, you can add 1 to hit and wound rolls for the bearer until the end of the phase. However, if no wounds are allocated as a result of these attacks, then the bearer suffers D3 mortal wounds.',
			'Ruby Vail' : 'Once per battle, in your hero phase, you can declare that the bearer will open the Ruby Vial. If you do so, then until your next hero phase, subtract 1 from the Bravery characteristic of enemy units and subtract 1 from the result of any charge rolls made for them.',
		},
	},
	death : {
		armyname : 'Allegiance: DEATH',
		commandability : {
			'Inspiring Presence' : '#',
		},
		battletraits : {
			'Deathless Minions' : '#',
		},
		commandtraits : {
			'Ruler of the Night' : 'Friendly <b>DEATH</b> units are affected by the Deathless Minions battle trait if they are within 12\" of this general rather than only 6\".',
			'Predator of the Shadows' : 'Add 1 to hit and wound rolls for this general if they are in cover.',
			'Death Incarnate' : 'In your hero phase, pick an enemy unit within 3\" of this general and roll two dice. If the total rolled equals or exceeds the enemy unit\’s  Bravery, it suffers D3 mortal wounds.',
			'Master of the Black Arts' : 'This general is a <b>WIZARD</b> who knows the Arcane Bolt and Mystic Shield spells. If this general is already a <b>WIZARD</b>, add 1 to all of their casting and unbinding rolls.',
			'Red Fury' : 'Roll a dice after this general attacks in the combat phase. On a 5+ they can immediately pile in and attack again (any such attacks do not generate further attacks in this way).',
			'Supernatural Horror' : 'Double the number of models that flee from enemy units if they are within 12\" of this general in the battleshock phase.',
		},
		artefacts : {
			'Cursed Book' : 'Subtract 1 from the hit rolls of any unit within 3\" of the bearer unless it has the <b>DEATH</b> keyword.',
			'Cloak of Mists and Shadows' : 'In the combat phase, instead of piling in and attacking with the bearer, you can remove them from the battlefield and set them up again within 12\" of their original location and more than 3\" from any enemy models. If this is impossible, the bearer remains in their current location.',
			'Blade of Dark Summons' : 'Once per battle, in your hero phase, you can set up a <b>SUMMONABLE DEATH</b> unit wholly within 12\" of the bearer and more than 3\" from any enemy models, and add it to your army. The models in the unit must have a combined Wounds characteristic of no more than a 2D6 roll.',
			'Black Amulet' : 'Once per battle, in your hero phase, the bearer can unleash the magic stored in the Black Amulet. When it does so, pick an enemy unit within 12\" of the bearer. The unit you pick suffers a number of mortal wounds equal to the number of the current battle round. You cannot pick a unit with the <b>DEATH</b> keyword.',
			'Tomb Blade' : 'Pick one of the bearer’s melee weapons. For each wound roll of 6+ you make for this weapon, you can heal 1 wound allocated to the bearer or a friendly <b>DEATH</b> model within 6\" of the bearer.',
			'Ring of Immortality' : 'The first time the bearer is slain, before removing them from the battlefield, roll a dice. On a 3+ the bearer is not slain and D3 wounds allocated to them are healed (any excess damage is negated). Then, remove the bearer from the battlefield and set them up again within 18\" of their original location and more than 3\" from any enemy models.',
		},
	},
	nighthaunt : {
		armyname : 'Allegiance: NIGHTHAUNT',
		commandability : {
			'Inspiring Presence' : '#',
		},
		// battletraits : {
		// 	'Deathless Minions' : '#',
		// },
		// commandtraits : {
		// 	'Ruler of the Night' : 'Friendly <b>DEATH</b> units are affected by the Deathless Minions battle trait if they are within 12\" of this general rather than only 6\".',
		// 	'Predator of the Shadows' : 'Add 1 to hit and wound rolls for this general if they are in cover.',
		// 	'Death Incarnate' : 'In your hero phase, pick an enemy unit within 3\" of this general and roll two dice. If the total rolled equals or exceeds the enemy unit\’s  Bravery, it suffers D3 mortal wounds.',
		// 	'Master of the Black Arts' : 'This general is a <b>WIZARD</b> who knows the Arcane Bolt and Mystic Shield spells. If this general is already a <b>WIZARD</b>, add 1 to all of their casting and unbinding rolls.',
		// 	'Red Fury' : 'Roll a dice after this general attacks in the combat phase. On a 5+ they can immediately pile in and attack again (any such attacks do not generate further attacks in this way).',
		// 	'Supernatural Horror' : 'Double the number of models that flee from enemy units if they are within 12\" of this general in the battleshock phase.',
		// },
		// artefacts : {
		// 	'Cursed Book' : 'Subtract 1 from the hit rolls of any unit within 3\" of the bearer unless it has the <b>DEATH</b> keyword.',
		// 	'Cloak of Mists and Shadows' : 'In the combat phase, instead of piling in and attacking with the bearer, you can remove them from the battlefield and set them up again within 12\" of their original location and more than 3\" from any enemy models. If this is impossible, the bearer remains in their current location.',
		// 	'Blade of Dark Summons' : 'Once per battle, in your hero phase, you can set up a <b>SUMMONABLE DEATH</b> unit wholly within 12\" of the bearer and more than 3\" from any enemy models, and add it to your army. The models in the unit must have a combined Wounds characteristic of no more than a 2D6 roll.',
		// 	'Black Amulet' : 'Once per battle, in your hero phase, the bearer can unleash the magic stored in the Black Amulet. When it does so, pick an enemy unit within 12\" of the bearer. The unit you pick suffers a number of mortal wounds equal to the number of the current battle round. You cannot pick a unit with the <b>DEATH</b> keyword.',
		// 	'Tomb Blade' : 'Pick one of the bearer’s melee weapons. For each wound roll of 6+ you make for this weapon, you can heal 1 wound allocated to the bearer or a friendly <b>DEATH</b> model within 6\" of the bearer.',
		// 	'Ring of Immortality' : 'The first time the bearer is slain, before removing them from the battlefield, roll a dice. On a 3+ the bearer is not slain and D3 wounds allocated to them are healed (any excess damage is negated). Then, remove the bearer from the battlefield and set them up again within 18\" of their original location and more than 3\" from any enemy models.',
		// },
	},
}

var magic = {
	lorebasic : {
		magicname : 'Basic spells',
		'Arcane Bolt' : {
			cast:'5',
			range:'18 in LoS',
			target:'enemy unit',
			effect:'The unit you pick up suffers D3 mortal wounds.',
		},
		'Mystic Shield' : {
			cast:'6',
			range:'18 in LoS',
			target:'caster or friendly unit',
			effect:'You can add 1 to all save rolls for the unit you pick until the start of your next hero phase.',
		},
	},
	loreofdeathmages : {
		magicname : 'LORE OF THE DEATHMAGES',
		'OVERWHELMING DREAD' : {
			cast:'5',
			range:'18 in LoS',
			target:'enemy unit',
			effect:'Until your next hero phase, subtract 1 from hit rolls for that unit and subtract 1 from that unit’s Bravery characteristic.',
		},
		'FADING VIGOUR' : {
			cast:'6',
			range:'18 in LoS',
			target:'enemy unit',
			effect:'Until the start of your next hero phase, subtract 1 from the Attacks characteristic of that unit’s melee weapons (to a minimum of 1), and roll only a single dice when making charge rolls for it.',
		},
		'SPECTRAL GRASP' : {
			cast:'6',
			range:'18 in LoS',
			target:'terrain feature',
			effect:'Until your next hero phase, halve the Move characteristic (rounding down) of enemy units within 3" of any terrain features affected by any Spectral Grasp spells at the start of their movement phase.',
		},
		'PRISON OF GRIEF' : {
			cast:'7',
			range:'12 in LoS',
			target:'enemy unit',
			effect:'Until your next hero phase, before a unit affected by any Prison of Grief spells moves, roll a dice. On a 5+ the unit may not move in that phase.',
		},
		'DECREPIFY' : {
			cast:'6',
			range:'18 in LoS',
			target:'enemy <b>HERO</b> ',
			effect:'Until your next hero phase, subtract 1 from wound rolls made for that model and subtract 1 from the Damage characteristics of that model’s melee weapons (to a minimum of 1).',
		},
		'SOUL HARVEST' : {
			cast:'7',
			range:'( 3 )',
			target:'each enemy unit',
			effect:'If successfully cast, each enemy unit within 3" of the caster suffers D3 mortal wounds. Then, roll a dice for each mortal wound that was allocated to an enemy unit and not negated. For each 5+, heal 1 wound that has been allocated to the caster.',
		},
	},
	loreofvampires : {
		magicname : 'LORE OF THE VAMPIRES',
		'BLADES OF SHYISH' : {
			cast:'5',
			range:'( 12 )',
			target:'Each enemy unit',
			effect:'Roll a dice for each enemy unit within 12\" of the caster. On a 5+ that unit suffers 1 mortal wound.',
		},
		'SPIRIT GALE' : {
			cast:'6',
			range:'12 in LoS',
			target:'enemy unit',
			effect:'Roll 3D6. For each 5+, that unit suffers 1 mortal wound. In addition, if 2 of these dice show the same number, substract 1 from hit rolls for that unit until your next hero phase. If all 3 dice show the same number, substract 1 from hit and wound rolls for that unit until your next hero phase instead.',
		},
		'VILE TRANSFERENCE' : {
			cast:'7',
			range:'12 in LoS',
			target:'enemy unit',
			effect:'Pick an enemy unit within 12\" of the caster that is visible to them, and a friendly DEATH unit within 6" of that enemy unit. The enemy unit suffers D3 mortal wounds. Then, for each of these wounds that was allocatad and not negated, you can heal 1 wound allocated to the friendly unit.',
		},
		'AMETHYSTINE PINIONS' : {
			cast:'5',
			range:'self',
			target:'self',
			effect:'Until your next hero phase add 5\" to the caster\'s Move characteristic and the caster can fly.',
		},
		'SOULPIKE' : {
			cast:'6',
			range:'18 in LoS',
			target:'enemy unit',
			effect:'Until your next hero phase, after a unit affected by any Soulpike spells makes a charge move, roll a number of dice equal to the result of their charge roll. For each 5+, that unit suffers 1 mortal wound.',
		},
		'AMARANTITE ORB' : {
			cast:'7',
			range:'12',
			target:'point',
			effect:'Pick a point on the battlefield within 12\" of the caster and draw an imaginary straight line 1mm wide between that point and the closest part of the caster. Roll a dice for each unit (friend or foe, apart from the caster) that has any models beneath this line. On a 4+ that unit suffers D6 mortal wounds.',
		},
	},
}

var units = {
		basic : {
			name:'NAME',
			role:'ROLE',
			move:'MOVE',
			wounds:'WOUNDS',
			bravery:'BRAVERY',
			save:'SAVE',
			points:'PTS',
			weapon : {
				'WEAPON_NAME_1' : {
					type:'TYPE',
					range:'RANGE',
					attacks:'ATTACKS',
					tohit:'TOHIT',
					towound:'TOWOUND',
					rend:'REND',
					damage:'DMG',
				},
				'WEAPON_NAME_2' : {
					type:'TYPE',
					range:'RANGE',
					attacks:'ATTACKS',
					tohit:'TOHIT',
					towound:'TOWOUND',
					rend:'REND',
					damage:'DMG',
				},
			},
			abilities : {
				'ABILITY_1' : 'ABILITY_1_TEXT',
				'ABILITY_2' : 'ABILITY_2_TEXT',
			},
			spell : {
				'Arcane Bolt' : {
					cast:'5',
					range:'18 in LoS',
					target:'enemy unit',
					effect:'The unit you pick up suffers D3 mortal wounds.',
				},
				'Mystic Shield' : {
					cast:'6',
					range:'18 in LoS',
					target:'caster or friendly unit',
					effect:'You can add 1 to all save rolls for the unit you pick until the start of your next hero phase.',
				},
			},
			command : {
				'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero pse.',
			},
			keywords:'KEYWORD_1, KEYWORD_2',
		},
		// basilio : {
		// 	bravery:'BRAVERY',
		// 	save:'SAVE',
		// 	points:'PTS',
		// 	weapon : {
		// 		'WEAPON_NAME_1' : {
		// 			type:'TYPE',

		// 			attacks:'ATTACKS',

		// 			rend:'REND',
		// 			damage:'DMG',
		// 		},
		// 		'WEAPON_NAME_2' : {
		// 			type:'TYPE',
		// 			range:'RANGE',
		// 			attacks:'ATTACKS',
		// 			tohit:'TOHIT',
		// 			towound:'TOWOUND',
		// 			rend:'REND',
		// 			damage:'DMG',
		// 		},
		// 	},
		// 	abilities : {

		// 		'' : 'ABILITY_2_TEXT',
		// 		'^_^' : '',
		// 	},


		// 	command : {
		// 		'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero pse.',
		// 	},
		// 	keywords:'',
		// },
	//	LEADER
		vampirelord : {
			name:'Vampire Lord',
			role:'Leader',
			move:'5 (10)',
			wounds:'5',
			bravery:'10',
			save:'4+',
			points:'140',
			icon:'soulblight',
			weapon : {
				'Spirit-possesed Blades' : {
					type:'melee',
					range:'1',
					attacks:'4',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'D3',
				},
			},
			abilities : {
				'Flying Horror' : 'Vampire Lord with wings have Move 10" and can fly.',
				'Chalice of Blood' : 'Once per battle, in your hero phase, a Vampire Lord with a Chalice of Blood heals D6 wounds.',
				'The Hunger' : '#',
				'Deathly Invocation' : 'At the start of your hero phase, pick up to 3 different friendly <b>SUMMONABLE</b> units within 12" of this model. You can heal D3 wounds that have been allocated to each unit you picked (roll separately for each unit). If no wounds are currently allocated to a unit you have picked, you may instead return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
				'Wizard' : 'Can attempt to cast one spell in each of your hero phases, and attempt to unbind one spell in each enemy hero phase.',
				},
			spell : {
			},
			loreofvampires : {},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
				'Blood Feast' : 'Pick a friendly <b>Death</b> unit within 15". Models in that unit make one extra attack with each of their melee weapons until your next hero phase.',
			},
			keywords:'DEATH, LEGION, VAMPIRE, SOULBLIGHT, HERO, WIZARD, VAMPIRE LORD',
		},
		necromancer : {
			name:'Necromancer',
			role:'Leader',
			move:'5',
			wounds:'5',
			bravery:'10',
			save:'6+',
			points:'110',
			icon:'deathmages',
			weapon : {
				'Necromancer\'s Staff' : {
					type:'melee',
					range:'2',
					attacks:'1',
					tohit:'4+',
					towound:'3+',
					rend:'-1',
					damage:'D3',
				},
			},
			abilities : {
				'Undead minions' : 'Before you allocate a wound to this model, you may pick a friendly <b>SUMMONABLE</b> unit within 3\" and roll a dice. On a 4+ the wound is allocated to that unit instead.',
				'Deathly Invocation' : 'At the start of your hero phase, pick up to 2 different friendly <b>SUMMONABLE</b> units within 6\" of this model. You can heal D3 wounds that have been allocated to each unit you picked (roll separately for each unit). If no wounds are currently allocated to a unit you have picked, you may instead return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
				'Wizard' : 'Can attempt to cast one spell in each of your hero phases, and attempt to unbind one spell in each enemy hero phase.',
				},
			spell : {
				'Vanhel\'s Dance Macabre' : {
					cast:'6',
					range:'18',
					target:'friendly <b>SUMMONABLE</b> unit',
					effect:'That unit can be chosen to pile in and attack twice in your next combat phase.',
				},
			},
			loreofdeathmages : {},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
			},
			keywords:'DEATH, LEGION, DEATHMAGES, HERO, WIZARD, NECROMANCER',
		},
		knightofshrouds : {
			name:'Knight of Shrouds',
			role:'Leader',
			move:'6',
			wounds:'5',
			bravery:'10',
			save:'4+',
			points:'120',
			icon:'nighthaunt',
			weapon : {
				'Sword of Stolen Hours' : {
					type:'melee',
					range:'1',
					attacks:'4',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'2',
				},
			},
			abilities : {
				'FLY' : '#',
				'Ethereal' : '#',
				'Stolen Hours' : 'Each time a wound inflicted by this model\'s Sword of Stolen Hours slays an enemy <b>HERO</b>, heal 1 wound allocated to this model.',
				},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
				'Spectral Overseer' : 'In the combat phase of this turn, add 1 to hit rolls for friendly <b>NIGHTHAUNT</b> models while they are within 9" of this model.',
			},
			keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, HERO, KNIGHT OF SHROUDS',
		},
		wightking1 : {
			name:'Wight King (Tomb Blade)',
			role:'Leader',
			move:'4',
			wounds:'5',
			bravery:'10',
			save:'3+',
			points:'120',
			icon:'deathrattle',
			weapon : {
				'Baleful Tomb Blade' : {
					type:'melee',
					range:'1',
					attacks:'4',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
			},
			abilities : {
				'Beheading Strike' : 'If the wound roll for an attack made with a Baleful Tomb Blade is 6+, that attack has a Damage characteristic of D3.',
				'Deathly Invocation' : 'At the start of your hero phase, pick up to 2 different friendly <b>SUMMONABLE</b> units within 6" of this model. You can heal D3 wounds that have been allocated to each unit you picked (roll separately for each unit). If no wounds are currently allocated to a unit you have picked, you may instead return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
			},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
				'Lord of Bones' : 'Pick a friendly <b>DEATHRATTLE</b> unit within 18". Until your next hero phase, add 1 to the Attacks characteristic of that unit\'s melee weapons.',
			},
			keywords:'DEATH, LEGION, SKELETON, DEATHRATTLE, HERO, WIGHT KING',
		},
		wightking2 : {
			name:'Wight King (Black Axe)',
			role:'Leader',
			move:'4',
			wounds:'5',
			bravery:'10',
			save:'3+',
			points:'120',
			icon:'deathrattle',
			weapon : {
				'Black Axe' : {
					type:'melee',
					range:'1',
					attacks:'4',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
			},
			abilities : {
				'Black Axe' : 'If a model is allocated any wounds from attacks made using the Black Axe but is not slain, roll a dice after the Wight King has finished making all of its attacks. On a 6+ that model is slain.',
				'Barrow Armour' : 'Halve the number of wounds allocated to this model from each attack, rounding up (the remainder are negated).',
				'Deathly Invocation' : 'At the start of your hero phase, pick up to 2 different friendly <b>SUMMONABLE</b> units within 6" of this model. You can heal D3 wounds that have been allocated to each unit you picked (roll separately for each unit). If no wounds are currently allocated to a unit you have picked, you may instead return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D3.',
			},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
				'Lord of Bones' : 'Pick a friendly <b>DEATHRATTLE</b> unit within 18". Until your next hero phase, add 1 to the Attacks characteristic of that unit\'s melee weapons.',
			},
			keywords:'DEATH, LEGION, SKELETON, DEATHRATTLE, HERO, WIGHT KING',
		},
		tombbanshee : {
			name:'TOMB BANSHEE',
			role:'Leader',
			move:'6',
			wounds:'4',
			bravery:'10',
			save:'4+',
			points:'80',
			icon:'nighthaunt',
			weapon : {
				'Ghostly Howl' : {
					type:'missile',
					range:'10',
					attacks:'1',
					tohit:'*',
					towound:'*',
					rend:'*',
					damage:'*',
				},
				'Chill Dagger' : {
					type:'melee',
					range:'1',
					attacks:'1',
					tohit:'4+',
					towound:'3+',
					rend:'-2',
					damage:'D3',
				},
			},
			abilities : {
				'FLY' : '#',
				'Ethereal' : '#',
				'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Chill Dagger, that attack inflicts D3 mortal wounds instead of the normal damage (do not make a wound or save roll).',
				'Ghostly Howl' : 'When making a Ghostly Howl attack, pick a target within range, roll 2D6; if the total is higher than that unit\'s Bravery, it suffers a number of mortal wounds equal to the difference.',
				},
			command :{
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
			},
			keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, HERO, TOMB BANSHEE',
		},
		cairnwraith : {
			name:'CAIRN WRAITH',
			role:'Leader',
			move:'6',
			wounds:'4',
			bravery:'10',
			save:'4+',
			points:'60',
			icon:'nighthaunt',
			weapon : {
				'Reaper Scythe' : {
					type:'melee',
					range:'2',
					attacks:'3',
					tohit:'4+',
					towound:'3+',
					rend:'-1',
					damage:'2',
				},
			},
			abilities : {
				'FLY' : '#',
				'Ethereal' : '#',
				'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Reaper Scythe, that attack inflicts 2 mortal wounds instead of the normal damage.',
				'Reaped Like Corn' : 'If the target unit has 5 or more models, you can re-roll failed hit rolls for this model\'s Reaper Scythe.',
				},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
			},
			keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, HERO, CAIRN WRAITH',
		},

		/*NIGHTHAUNT*/
		guardianofsouls : {
			name:'Guardian of Souls',
			role:'Leader',
			move:'6',
			wounds:'5',
			bravery:'10',
			save:'4+',
			points:'',
			icon:'nighthaunt',
			weapon : {
				'Chill Blade' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
			},
			abilities : {
				'FLY' : '#',
				'Ethereal' : '#',
				'Nightmare Lantern' : 'Add 1 to wound rolls for melee weapons wielded by friendly <b>NIGHTHAUNT</b> models that are within 9\" of this model.',
				'Wizard' : 'Can attempt to cast one spell in your hero phase, and attempt to unbind one spell in the enemy hero phase.',
				},
			spell:{
				'Spectral Lure' : {
					cast:'6',
					range:'18',
					target:'friendly <b>SUMMONABLE NIGHTHAUNT</b> unit',
					effect:'Pick a friendly <b>SUMMONABLE NIGHTHAUNT</b> unit wholly within 18\" of the caster. You can either heal D6 wounds that have been allocated to that unit or, if no wounds are currently allocated to the unit, you may return a number of slain models to it that have a combined Wounds characteristic equal to or less than the roll of a D6.',
				},
			},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
				// 'Spectral Overseer' : 'In the combat phase of this turn, add 1 to hit rolls for friendly <b>NIGHTHAUNT</b> models while they are within 9" of this model.',
			},
			keywords:'DEATH, MALIGNANT, NIGHTHAUNT, HERO, WIZARD, GUARDIAN OF SOULS',
		},
		lordexecutioner : {
			name:'Lord Executioner',
			role:'Leader',
			move:'6',
			wounds:'5',
			bravery:'10',
			save:'4+',
			points:'',
			icon:'nighthaunt',
			weapon : {
				'Decapitating Greataxe' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'3+',
					towound:'3+',
					rend:'-2',
					damage:'1',
				},
			},
			abilities : {
				'FLY' : '#',
				'Ethereal' : '#',
				'Beheading Strike' : 'If a wound roll for a Decapitating Greataxe is 6+, add 2 to the Damage characteristic of the weapon for that attack.',
				'Staring Death in the Face' : 'At the start of the combat phase, you can pick an enemy <b>Hero</b> within 3\" of this model. Substract 1 from hit rolls for attacks made by that <b>Hero</b> in that combat phase.',
				'Disembodied Skulls' : 'Roll a D6 each time this model suffers a mortal wound. On a 5+, the wound is negated.',
				},
			command : {
				// 'Inspiring Presence' : 'Pick a unit from your army that is within 12" of your general. That unit does not have to take battleshock tests until your next hero phase.',
				// 'Spectral Overseer' : 'In the combat phase of this turn, add 1 to hit rolls for friendly <b>NIGHTHAUNT</b> models while they are within 9" of this model.',
			},
			keywords:'DEATH, MALIGNANT, NIGHTHAUNT, HERO, LORD EXECUTIONER',
		},
		chainrasphorde : {
			name:'Chainrasp Horde (-)',
			// role:'Battleline Nighthaunt',
			move:'6',
			wounds:'1',
			bravery:'6',
			save:'5+',
			points:'',
			icon:'nighthaunt',
			weapon : {
				'Dreadwarden\'s Malignant Weapon' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'4+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
				'Malignant Weapon' : {
					type:'melee',
					range:'1',
					attacks:'2',
					tohit:'4+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
			},
			abilities : {
				'DREADWARDEN' : 'The leader of this unit is Dreadwarden. Add 1 to the Attacks characteristic of a Dreadwarden\'s Malignant Weapon. In addition, a Chainrasp Horde has a Bravery characteristic of 10 instead of 6 while it includes a Dreadwarden.',
				'FLY' : '#',
				'Ethereal' : '#',
				'Chilling Horde' : 'Re-roll wound rolls of 1 for this unit while it has more than 10 models.',
				},
			keywords:'DEATH, MALIGNANT, NIGHTHAUNT, SUMMONABLE, CHAINRASP HORDE',
		},
	//	BATTLELINE	
		direwolves : {
			name:'Dire Wolves (5-30)',
			role:'Battleline',
			move:'10',
			wounds:'2',
			bravery:'10',
			save:'5+',
			points:'60',
			// points:'60/320',
			weapon : {
				'Doom Wolf\'s Rotting Fangs and Claws' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'4+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
				'Rotting Fangs and Claws' : {
					type:'melee',
					range:'1',
					attacks:'2',
					tohit:'4+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
			},
			abilities : {
				'Doom Wolf' : 'The leader of this unit is Doom Wolf. Add 1 to the Attacks characteristic of a Doom Wolf\'s Rotting Fangs and Claws.',
				'Slavering Charge' : 'Add 1 to wound rolls for this unit if it completed a charge move this turn.',
				'Vigour Necris' : 'Add 1 to save rolls for this unit if it is within 9\" of any friendly <b>CORPSE CARTS</b>.',
				},
			keywords:'DEATH, LEGION, ZOMBIE, DEADWALKERS, SUMMONABLE, DIRE WOLVES',
		},
		skeletonwarriors : {
			name:'Skeleton Warriors (10-40)',
			role:'Battleline',
			move:'4',
			wounds:'1',
			bravery:'10',
			save:'6+',
			points:'80',
			icon:'deathrattle',
			// points:'280',
			weapon : {
				'Skeleton champion\'s Ancient Blade' : {
					type:'melee',
					range:'1',
					attacks:'2',
					tohit:'4+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
				'Skeleton champion\'s Ancient Spear' : {
					type:'melee',
					range:'2',
					attacks:'2',
					tohit:'5+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
				'Ancient Blade' : {
					type:'melee',
					range:'1',
					attacks:'1',
					tohit:'4+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
				'Ancient Spear' : {
					type:'melee',
					range:'2',
					attacks:'1',
					tohit:'5+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
			},
			abilities : {
				'Skeleton champion' : 'The leader of this unit is Skeleton champion. Add 1 to the Attacks characteristic of a Skeleton champion\'s Ancient Blade or Ancient Spear.',
				'Serve in Death' : '#' ,
				'Skeleton Legion' : 'Add 1 to the Attacks characteristic of this unit\’s melee weapons if it has 20 or more models. Add 2 instead if it has 30 or more models.',
				'Crypt Shields' : '#',
				'Standard Bearer' : '#',
				'Hornblower' : '#',
				},
			keywords:'DEATH, LEGION, SKELETON, DEATHRATTLE, SUMMONABLE, SKELETON WARRIORS',
		},
		hexwraiths : {
			name:'Hexwraiths (5-20)',
			role:'Battleline Nighthaunt',
			move:'12',
			wounds:'2',
			bravery:'10',
			save:'4+',
			points:'160',
			icon:'nighthaunt',
			weapon : {
				'Hellwraith\'s Spectral Scythe' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'4+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
				'Spectral Scythe' : {
					type:'melee',
					range:'1',
					attacks:'2',
					tohit:'4+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
				'Skeletal Steed\'s Hooves and Teeth' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'4+',
					towound:'5+',
					rend:'-',
					damage:'1',
				},
			},
			abilities : {
				'HELLWRAITH' : 'The leader of this unit is Hellwraith. Add 1 to the Attacks characteristic of a Hellwraith\'s Spectral Scythe.',
				'FLY' : '#',
				'Ethereal' : '#',
				'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Spectral Scythe, that attack inflicts 1 mortal wound instead of the normal damage (do not make a wound or save roll).',
				'Spectrum Hunter\'s' : 'In the movement phase, immediately after this unit has moved, you can pick an enemy unit that was passed across by any models from this unit. If you do so, roll a dice for each Hexwraith that passed across that enemy unit. For each roll of 5+, that enemy unit suffers 1 mortal wound.',
				},
			keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, SUMMONABLE, HEXWRAITHS',
		},
		spirithosts : {
			name:'Spirit Hosts (3-12)',
			role:'Battleline Nighthaunt',
			move:'6',
			wounds:'3',
			bravery:'10',
			save:'4+',
			points:'120',
			icon:'nighthaunt',
			weapon : {
				'Spectral Claws and Daggers' : {
					type:'melee',
					range:'1',
					attacks:'6',
					tohit:'5+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
			},
			abilities : {
				'FLY' : '#',
				'Ethereal' : '#',
				'Frightful Touch' : 'If the hit roll for an attack made by a Spirit Host is 6+, immediately inflict 1 mortal wound instead of its normal damage.',
				},
			keywords:'DEATH, LEGION, MALIGNANT, NIGHTHAUNT, SUMMONABLE, SPIRIT HOSTS',
		},
		bloodknights : {
			name:'Blood Knights (5-15)',
			role:'Battleline Soulblight',
			move:'10',
			wounds:'3',
			bravery:'10',
			save:'4+',
			points:'260',
			icon:'soulblight',
			weapon : {
				'Kastellan\'s Templar Lance or Blade' : {
					type:'melee',
					range:'1',
					attacks:'4',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
				'Templar Lance or Blade' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
				'Nightmare\'s Hooves and Teeth' : {
					type:'melee',
					range:'1',
					attacks:'2',
					tohit:'4+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
			},
			abilities : {
				'Kastellan' : 'The leader of this unit is Kastellan. Add 1 to the Attacks characteristic of a Kastellan\'s Templar Lance or Blade.',
				'The Hunger' : '#',
				'Martial Fury' : 'If this unit completed a charge this turn, increase the Damage characteristic of its Templar Lances or Blades to D3.',
				'Bloodshields' : 'Add 1 to the save rolls for a unit carrying Bloodshields against attacks that have a Rend characteristic of "-".',
				'Standard Bearer' : '#',
				'Hornblower' : '#',
				},
			keywords:'DEATH, LEGION, VAMPIRE, SOULBLIGHT, BLOOD KNIGHTS',
		},
		graveguard : {
			name:'Grave Guard (5-30)',
			role:'Battleline Host of Nagash',
			move:'4',
			wounds:'1',
			bravery:'10',
			save:'5+',
			points:'80',
			icon:'deathrattle',
			// points:'420',
			weapon : {
				'Seneschal\'s Wight Blade' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'3+',
					towound:'4+',
					rend:'-1',
					damage:'1',
				},
				'Seneschal\'s Great Wight Blade' : {
					type:'melee',
					range:'1',
					attacks:'3',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
				'Wight Blade' : {
					type:'melee',
					range:'1',
					attacks:'2',
					tohit:'3+',
					towound:'4+',
					rend:'-1',
					damage:'1',
				},
				'Great Wight Blade' : {
					type:'melee',
					range:'1',
					attacks:'2',
					tohit:'3+',
					towound:'3+',
					rend:'-1',
					damage:'1',
				},
			},
			abilities : {
				'Seneschal' : 'The leader of this unit is Seneschal. Add 1 to the Attacks characteristic of a Seneschal\'s Wight Blade or Great Wight Blade.',
				'Cursed Weapons' : 'If the wound roll for an attack made with a Wight Blade or Great Wight Blade is 6+, double the damage characteristic of that attack.',
				'Crypt Shields' : '#',
				'Standard Bearer' : '#',
				'Hornblower' : '#',
				},
			keywords:'DEATH, LEGION, SKELETON, DEATHRATTLE, SUMMONABLE, GRAVE GUARD',
		},
	//	BEHEMOTH
		mortisengine : {
			name:'Mortis Engine',
			role:'Behemoth',
			move:'14 | 12 | 10 | 8 | 4',
			wounds:'2|3-4|5-7|8-9|10-12',
			bravery:'10',
			save:'4+',
			points:'180',
			icon:'deathmages',
			/*
			degradation table
			wailrg attacks move dmg
			9		12 		14 	0-2
			8		10 		12 	3-4
			7		8 		10 	5-7
			6		6 		8 	8-9
			5		4 		4 	10+
			*/
			weapon : {
				'Wail of the Damned' : {
					/*see below*/
					type:'missile',
					range:'9 | 8 | 7 | 6 | 5',
					attacks:'*',
					tohit:'*',
					towound:'*',
					rend:'*',
					damage:'*',
				},
				'Corpsemaster\'s Mortis Staff' : {
					type:'melee',
					range:'1',
					attacks:'1',
					tohit:'4+',
					towound:'3+',
					rend:'-1',
					damage:'D3',
				},
				'Spectral Host\'s Ethereal Weapons' : {
					type:'melee',
					range:'1',
					attacks:'12 | 10 | 8 | 6 | 4',
					tohit:'5+',
					towound:'4+',
					rend:'-',
					damage:'1',
				},
			},
			abilities : {
				'FLY' : '#',
				'Frightful Touch' : 'Each time you make a hit roll of 6+ for a Spectral Host\'s Ethereal Weapons, that attack inflicts 1 mortal wound instead of the normal damage (do not make a wound or save roll).',
				'Wail of the Damned' : 'When making a Wail of the Damned attack, roll 2D6 for each enemy unit within the range shown on the damage table. If the total is higher than that unit\'s Bravery, it suffers D3 mortal wounds.',
				'The Reliquary' : 'Once per battle, in hero phase roll 4D6. Each unit within that many inches affected. <b>Death</b> units heal D3 wounds, but any other unit suffers D3 mortal wounds.',
				'Bound Necromancer' : 'Add 1 to casting rolls for Death Wizards within 12" of any Mortis Engines. Substract 1 from casting rolls for Order, Destruction and Chaos Wizards within 12" of any Mortis Engines.',
				},
			keywords:'DEATH, LEGION, MALIGNANT, DEATHMAGES, MORTIS ENGINE',
		},
	sepulcharguard : {
		name:'THE SEPULCHAR GUARD',
		role:'',
		move:'4',
		wounds:'1',
		bravery:'10',
		save:'6+',
		points:'80',
		icon:'deathrattle',
		weapon : {
			'Sepulchar Warden\'s Ancient Spear' : {
				type:'melee',
				range:'2',
				attacks:'3',
				tohit:'4+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
			'Petitioner\'s Ancient Blade (3)' : {
				type:'melee',
				range:'1',
				attacks:'1 (3)',
				tohit:'4+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
			'Champion\'s Ancient Greatblade' : {
				type:'melee',
				range:'1',
				attacks:'2',
				tohit:'4+',
				towound:'4+',
				rend:'-1',
				damage:'1',
			},
			'Prince\'s of Dust Ancient Mace' : {
				type:'melee',
				range:'1',
				attacks:'2',
				tohit:'4+',
				towound:'3+',
				rend:'-',
				damage:'1',
			},
			'Harvester\'s Ancient Scythe' : {
				type:'melee',
				range:'1',
				attacks:'1',
				tohit:'4+',
				towound:'3+',
				rend:'-',
				damage:'2',
			},
		},
		abilities : {
			'Crypt Shields' : '#',
			'Serve in Death' : '#',
			'Frightening Speed' : 'You can re-roll charge rolls for this unit.',
			'The Sepulchar Warden' : 'In each of your hero phases you can return D3 slain models to this init while the Sepulchar Warden is on the battlefield.',
			'unique' : 'Only one of this unit can be included in a Pitched Battle army.',
		},
		keywords:'DEATH, SKELETON, DEATHRATTLE, SKELETON WARRIORS, THE SEPULCHAR GUARD',
	},
	batswarms : {
		name:'Bat Swarms (2-8)',
		role:'',
		move:'12',
		wounds:'5',
		bravery:'10',
		save:'-',
		points:'80',
		icon:'soulblight',
		weapon : {
			'Razor-sharp Teeth' : {
				type:'melee',
				range:'3',
				attacks:'5',
				tohit:'5+',
				towound:'5+',
				rend:'-',
				damage:'1',
			},
		},
		abilities : {
			'FLY' : 'Bat Swarms can fly.',
			'Cloud of Horror' : 'Substract 1 from hit rolls for enemy units that are within 12" of any Bat Swarms in the Shooting phase.',
			'Blood Suckers' : 'At the end of any combat phase in which this unit caused any wounds to be allocated to any enemy models, you can heal all wounds that have been allocated to this unit.',
			},
		keywords:'DEATH, LEGION, SOULBLIGHT, SUMMONABLE, BAT SWARMS',
	},
	fellbats : {
		name:'Fell Bats (3-12)',
		role:'',
		move:'14',
		wounds:'3',
		bravery:'10',
		save:'6+',
		points:'80',
		icon:'soulblight',
		weapon : {
			'Elongated Fangs' : {
				type:'melee',
				range:'1',
				attacks:'2',
				tohit:'4+',
				towound:'4+',
				rend:'-',
				damage:'1',
			},
		},
		abilities : {
			'FLY' : 'Bat Swarms can fly.',
			'Scent of Gore' : 'If an enemy model is slain within 6" of this unit, increase the Attacks characteristic of this unit\'s Elongated Fangs to 6 for the rest of the battle.',
			},
		keywords:'DEATH, LEGION, SOULBLIGHT, SUMMONABLE, FELL BATS',
	},
	vargheists : {
		name:'Vargheists (3-12)',
		role:'',
		move:'12',
		wounds:'4',
		bravery:'10',
		save:'5+',
		points:'160',
		icon:'soulblight',
		weapon : {
			'Vargoyle\'s Murderous Fangs and Talons' : {
				type:'melee',
				range:'1',
				attacks:'4',
				tohit:'3+',
				towound:'3+',
				rend:'-1',
				damage:'2',
			},
			'Murderous Fangs and Talons' : {
				type:'melee',
				range:'1',
				attacks:'3',
				tohit:'3+',
				towound:'3+',
				rend:'-1',
				damage:'2',
			},
		},
		abilities : {
			'FLY' : '',
			'Vargoyle' : 'The leader of this unit is Vargoyle. Add 1 to the Attacks characteristic of a Vargoyle\'s Murderous Fangs and Talons.',
			'Blood-maddened Feeding Frenzy' : 'Each time a model from this unit slays an enemy model, roll a dice. On a 6+ it can immediately make one additional attack against the same unit.',
			},
		keywords:'DEATH, LEGION, VAMPIRE, SOULBLIGHT, VARGHEISTS',
	},
}